version: '3.8'

services:
  server:
    build: .
    ports: 
      - '3001:3001'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postresql/data

volumes:
  data: